#ifndef CMAKE_PROJECT_TEMPLATE_CMAKE_PROJECT_TEMPLATE_LIBSRC_H
#define CMAKE_PROJECT_TEMPLATE_CMAKE_PROJECT_TEMPLATE_LIBSRC_H

#include <iostream>

void hello_world();

#endif // CMAKE_PROJECT_TEMPLATE_CMAKE_PROJECT_TEMPLATE_LIBSRC_H
