# cmake/toolchains/cmake_tool_chain_file_sample.cmake
set(CMAKE_CROSSCOMPILING OFF)

set(CMAKE_GENERATOR ${YOUR_TARGET_CMAKE_GENERATOR})
set(CMAKE_C_COMPILER ${YOUR_TARGET_CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${YOUR_TARGET_CMAKE_CXX_COMPILER})
set(CMAKE_LINKER ${YOUR_TARGET_CMAKE_LINKER})
